# Generated by Django 3.2.18 on 2023-03-10 14:21

import backend.common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(max_length=20, validators=[backend.common.validators.validate_letters])),
                ('last_name', models.CharField(max_length=25, validators=[backend.common.validators.validate_letters])),
                ('phone', models.CharField(max_length=15, validators=[backend.common.validators.validate_phone_number])),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth_app.opportunitymachineuser')),
            ],
        ),
    ]
