# Generated by Django 3.2.18 on 2023-04-03 20:53

import backend.common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0004_profile_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(max_length=25)),
                ('price', models.FloatField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_group', to='opportunity_app.productgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=25)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.EmailField(max_length=254)),
                ('discount', models.IntegerField()),
                ('phone', models.CharField(max_length=15, validators=[backend.common.validators.validate_phone_number])),
                ('is_deleted', models.BooleanField(default=False)),
                ('managing_city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_city_office', to='auth_app.cityoffice')),
            ],
        ),
    ]
