# Generated by Django 3.2.18 on 2023-04-27 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunity_app', '0002_auto_20230404_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Lost', 'Lost'), ('Won', 'Won')], max_length=15, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='opportunity_client', to='opportunity_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opportunity_app.opportunity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opportunity_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='opportunity_products_list', through='opportunity_app.OpportunityProducts', to='opportunity_app.Product'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
