# Generated by Django 3.2.18 on 2023-05-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_app', '0007_alter_opportunity_opportunity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='opportunity_id',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='close_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='last_modified_date',
            field=models.DateField(),
        ),
    ]
