# Generated by Django 3.2.18 on 2023-04-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_app', '0003_auto_20230427_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Lost', 'Lost'), ('Won', 'Won')], max_length=15),
        ),
    ]
